- filter.js
- index.html
- normalize.css
- script.js
- styles.css
Originally at https://github.com/jdalt/twin-cities-aid-distribution-locations/pull/23
For reviewer:
Instructions to run locally:
1. `npm install`
2. `npm run dev`
3. navigate to http://localhost:8080/ in a browser
> Usability fixes

- filter.js
> class properties arent supported in safari, move filters to constructor

- styles.css
> Remove unecessary max-height, h/t @maxine

- README.md
- package.json
Update references to the live site and repo to reflect their new URLs.
> Update repo and prod URLs

- filter.js
- index.html
- script.js
- styles.css
#6 and #7 based on @samanpwbb's recommended approach
> Markers are currently html elements. We can use dom manipulation to hide them: when a filter is selected, apply a class to all markers that we want to hide, or apply a class to container around markers and then use CSS to hide markers not matching the active class.
@kmarekspartz's PR was first but I just wanted to check this version deploy on netlify
> Toggle filters

- index.html
> Change Data Source text wording

- index.html
- styles.css
> Add 'About this project' link

- index.html
Fixes https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/37
Screenshot:
> Add support email link

- index.html
- script.js
- styles.css
As a first contribution, I wanted to get my feet wet with some very slight UI enhancements. I added a slight border under the popup row label and slightly reduced the font size. 
I also removed random whitespace in the code as a stumbled on it.
Lastly, I started to break out the title pane with the filter pane so we can consider adding a 'hide filters' or hamburger menu or whatever to collapse the blue filter section if somebody wants more map realestate. Nothing too big.
Before Screenshot: 
After Screenshot:
> Minor UI enhancements

- PULL_REQUEST_TEMPLATE.md
This PR adds a PR template that includes a basic QA checklist. The main purpose of the checklist is to ensure we don't accidentally introduce regressions. This is especially important since this project is actively used and does not have automated tests.
> Create a pull request template with a qa checklist

- script.js
Changed the "seeking volunteers" button to appear in the presence of the string "yes" rather than any truthy value. 
Removes incorrect "needs volunteers" buttons.
> update volunteer button

- styles.css
Updated css property for h3 tags to be compliant with accessibility contrast standards (AAA and AA).
https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/59
> Improved neighborhood name contrast

- index.html
Adding google analytics snippet from #29
> Feature: Google Analytics

- PULL_REQUEST_TEMPLATE.md
Add steps to the PR template to test translations
We need to make sure translations keep working
- [-] Tapping on a marker on the map displays information about the marker in a popup.
- [-] Tapping the "Show list of locations" button replaces the map view with a list view.
- [-] Tapping an item in the list replaces the list view with a map view, and navigates the map to the tapped item on the map.
- [-] Tapping one of the ✅'s in the legend filters items on the map and in the list.
- [-] Chrome
- [-] Firefox
- [-] Edge
- [-] Safari
> Add Translation testing to PR template

- src/index.js
Fixes small visual defect where locations with no neighborhood show 'undefined'
Because it looks pertyier
> :bug: locations with no neighborhood show 'undefined'

- src/index.js
Add Somali, Amharic, and Oromo
> feat: add Somali, Amharic, Oromo

- README.md
- public/index.html
Reverts Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#113
@mc-funk raised some issues for this
* typos
* diverging from translations
* possible display issues from longer title
> Revert "Make branding more consistent"

- src/js/filter.js
> Add closed locations to the map

- .testcaferc.json
- .travis.yml
- package.json
- specs/functional/filter_spec.js
- specs/functional/help_dialog_spec.js
- specs/functional/language_button_spec.js
- specs/functional/list_locations_spec.js
- specs/helpers.js
Added additional tests to cover the cases from the list below. No frontend changes
Tests are good
> More testcafe

- README.md
- public/index.html
- src/index.js
Related to this discussion: https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/126#issuecomment-640254416
I also noticed a typo re: `.node-version` in the readme and updated it.
> Minor readme and aria-label updates

- src/styles/styles.css
Improved text in the list location view to be passing accessibility requirements.
#148
> Improved color/contrast for location list text

- src/index.js
Very small wording change to address https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/162
> Change 'currently closed' to 'not open now'

- public/index.html
Adds gtag link to hopefully track traffic at both our main domain and the new alias, map.tcmap.org.
Handle flyer traffic
> Support google tags for map.tcmap.org

- src/js/validator.js
Improves on work in #151 to validate color, latitude, and longitude data on frontend.
Improve reliability and more rapidly identify invalid data.
> Add lat, lng, and color format validation

- src/index.js
Enables tracking of user location - makes the location tracking button act as a toggle button that when active the user's location is actively monitored for changes. 
Addition to https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/220
> Turn trackUserLocation flag to true

- README.md
Removed documentation about finding the environment variables pinned in the Slack channel.
The environment variables aren't pinned in the channel. What's pinned is a link to the same file already mentioned in the README, which only organization members can read, so it's not useful to tell non-members to look there.
> removed "env vars are pinned" comment

- src/index.js
Find phone numbers and email addresses in any field where we're already finding URLs (accepting, not accepting, seeking volunteers, urgent need, notes), and render them as `tel:` and `mailto:` links.
I also split a really long and unreadable regexp into three somewhat shorter and slightly less unreadable regexps.
Implements #183. Makes it easier for map viewers to contact aid sites.
> render phone numbers and email addresses as links

- package-lock.json
- package.json
- src/index.js
Update url parsing to find distinct urls and use replaceall shim to replace all instances
Issue  #234
> Issue 234: Fix URL Replacement

- src/index.js
Add linebreaks in map popup for every linebreak in google sheet
Issue #231
> Issue 231: Add Linebreaks

- src/i18n/hin.json
- src/i18n/kar.json
Fixing typo causing Hindi translation of `open for receiving donations` to render in English
Same as above ^^
> Fix typo in receiving donations

- README.md
Updated URL for example spreadsheet in README. (No changes to map or code.)
Previous Example spreadsheet had been trashed by owner.
> Replaced example spreadsheet url

- src/index.js
Bugfix - some of our moment locales were not working because they were not imported.
> Import moment locales so translation of times works better

- public/index.html
- src/i18n/eng.json
Update voting resources phrasing & add google analytics tracking on link clicks
Makes link clearer to users
> Update link phrase and add analytics

- src/i18n/eng.json
- src/index.js
- src/js/validator.js
Adding chip to identify sites that do not require ID checks
Requested by sites
> add chip for no ID checks

- src/i18n/eng.json
- src/index.js
- src/js/validator.js
For sites that do not need ID but do require other information - indicate that
People should know if they will be asked other questions even if not for ID
> Add some info required qualification for No ID Needed sites

- Dockerfile
- README.md
- docker-build.sh
- docker-compose.yml
- docker-run.sh
Added `Dockerfile` and scripts to build/run docker image/container locally.
#227 
( replaces https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/253 )
> Containerize

- bin/tsv-with-translation-to-json
- docs/LANGUAGE_TRANSLATION.md
Add a bash script to take a google sheet with all translations on it and create a json object the TCMAP translation.js can use.
Make it easier to add translations like #264
> Create new bash script for generating language translations

- public/index.html
Enable hours may vary banner for Dec 24-Jan02
> Enable hours may vary banner for Dec 24-Jan02

- public/index.html
Remove hours banner
Time when hours vary is passed.
> hide hours banner

- src/index.js
Add warming sites back in
Accidentally got removed in the shift away from google sheets.
> Add warming sites back in

- public/index.html
> add hours banner back for mlk day

- src/index.js
- src/styles/components/map-popup.css
Add public transit sites to the map 
> Add public transit route section

- src/i18n/man.json
correct mistake with mandarin translation
> correct mistake with mandarin translation

- public/index.html
- src/index.js
Adjust hidden search 
Allow transit option fields to be searched.
> Issue 298/amaxama/public transit followup

- public/index.html
- src/styles/components/hours-banner.css
Add banner for tcmap hiatus
Reminder to users that info may be out of date this week.
> Add banner for tcmap hiatus

- src/index.js
> Move status logic to ui

- src/styles/components/location-card.css
> Add style to fix card content spacing issue

- public/index.html
> add hours banner for memorial day

- public/index.html
- src/i18n/eng.json
- src/index.js
- src/styles/components/cooling-banner.css
- src/styles/components/covid-banner.css
- src/styles/components/hours-banner.css
> Add banner for links to cooling sites

- public/index.html
> Show hours banner for July 5

- public/index.html
> Remove hours banner

- public/index.html
> Update ramsey county link

- public/index.html
> Add labor day hours banner & remove cooling banner

- public/index.html
- src/index.js
> Add analytics tracking for opening popups, remove labor day banner

- src/js/filter.js
> Comment out loading indicator

- public/index.html
> Enable hours banner
