Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations

- filter.js
Addresses remaining todo in [filtering additions issue](https://github.com/jdalt/twin-cities-aid-distribution-locations/issues/21) in old repo. 
if "open for receiving donations" or "open for distributing donations" (item 2) is checked, then spots that are "open for both" should be automatically displayed as well.
Current solution may create a weird UX thing where if someone tries to uncheck "open for both" when one of the other two "open" options are selected, they won't be able to. Options to address this: I can leave it how it is, let people uncheck "open for both" even when one of the other two "open" options are selected (what might that use case be though?), or hide "open for both" from the filtering menu (but still leave it as an item in the map's key).
> Final filtering addition

- README.md
This little nugget helped me when I wanted to point to a different copy of the spreadsheet in development. 
A further enhancement will be to extract the DATA_URL const into .env file or something similar.
> Update readme with notes about Google Sheets in Development

- index.html
- styles.css
- Use verbs at the beginning of each phrase.
- Use `.` at the end of each phrase.
- Namedrop GitHub like we namedrop Google Sheets.
- Put GitHub link on its own line, after the email link.
- Make GitHub link to the README.md rather than the repository root for easier reading by people less familiar with GitHub.
- Autoremove some unneeded whitespace.
Before:
After:
> Standardize the typography for links

- filter.js
"open for both" checkbox behavior:
* if "receiving" and/or "distributing" is checked,  "open for both" is automatically checked but disabled (you cannot uncheck it)
* if "receiving" AND "distributing" are UNchecked, "open for both" is checked and enabled (you can uncheck it)
Addressing bug @comeoneileen found yesterday in the simplest way possible. Simpler solution to the issue than #50 .
> simplest "open for both" checkbox fix

- index.html
- script.js
- styles.css
Reduce height of the title area on mobile. Break help/info out into it's own separate section and conditionally show/hide it when user clicks the button.
Title area takes up too much vertical space on small screens. Issue: https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/57
**Desktop screenshots**
**Mobile screenshots** (iPhone 5/SE size)
> Reduce title area height on mobile

- README.md
Updated the README to replace the deprecated template spreadsheet with the current one. Also fixed the OTC Slack link.
> docs: fix links in README.md

- index.html
Minor change to update the google sheets link from the "published for the web" version to a read-only shared version. This addresses issue https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/62
My big worry here is that the owners of the spreadsheet are going to start getting flooded with requests to edit the document, which I don't think we can avoid while also making filtering the data possible -- the way to hide the "View only" callout would be to publish the spreadsheet for the web, which is exactly what we're doing now.
> Update "See the data in Google Sheets" link

- filter.js
Uncheck the `unknown` and `closed` filter checkboxes on page load.
So the initial page load has less going on, and the call to action is clearer.
I haven't talked to anyone else about this, I just thought I'd throw up a PR and see if you liked it. 
Filters still work, you can still add back other sites when you click the checkbox.
> Uncheck unknown and closed sites on page load to make a clearer call to action

- index.html
- script.js
- styles.css
Moves up last updated on the map pins and uses `moment.js` to parse the date and spit out a nice string like `8 hours ago` or `2 days ago`. Display the unparsed date string as the `title` so desktop users can hover on it to get a more refined display. If we need something better for mobile users that can be done too (not sure what yet...).
I'm also not sure if you guys are down with adding another JS lib in the global namespace. Feel free to call that out. IMO the momentjs stuff isn't necessary to make this more prominent just kind of fun to have. 
Resolves https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/75
> Move up last updated, add momentjs, use momentjs to do "n hours ago" sentence

- README.md
- public/index.html
Align naming to "Twin Cities Mutual Aid Map". Adds link to https://tcmap.org.
Three names were in use:
- Twin Cities Aid Distribution Locations (README.md, public/index.html)
- Twin Cities Mutual Aid Map (CODE_OF_CONDUCT.md, https://tcmap.org)
- Twin Cities Aid Map (public/index.html)
> Make branding more consistent

- public/index.html
This change reverts the link to the Google Sheet back to Publish to Html version.
The readonly (rather than then publish to web version) leaks information that we wish to remain private.
> Link to "Public Html" Version of the Sheet

- src/index.js
- src/js/filter.js
This adds the count of each of the statusOptions available, as per issue #80
This aids in less confusion during nighttime hours when the map is empty -- it's more obvious that there are locations that are hidden. 
Also note that mobile view was checked as well, and no weird wrapping issues seem to occur.
> Adds count to map key, closes issue #80

- src/styles/welcome.css
Makes language selection modal scrollable
The number of languages causes issues on smaller screen sizes. See issue #123
> :bug: #123 make language selection modal scrollable

- src/index.js
Minor change to switch the translation-id for show/hide list button depending on its state
#121
> Issue #121

- src/index.js
Creates an hour range for the distribution and receiving hours, brought up in #122. Will need to add the new keys `distribution_hours` and `receiving_hours` to the translation spreadsheet for translation to work properly.
Having the hours on separate lines took up lots of space and was not as easy to read.
> adding range to hours

- src/index.js
Ignore `marker` and `popup` values from a location for rendering
Clicking on a location shows the content but "Marker" and "Popup" show up there with `[Object object]` as a value.
> Fix: "Marker" and "Popup" show up at the bottom of the map popups

- README.md
- docs/LANGUAGE_TRANSLATION.md
Add documentation for translation feature to address #106 and #131 
Make it easier to deal with translations
> Translation documentation

- README.md
Add link to default env file in new secret repo
It's hard to track this sort of thing on Slack
Resolves #135
> Add link to README for env variables

- package-lock.json
- package.json
- src/index.js
- src/js/filter.js
- src/js/url-helpers.js
- web_modules/dompurify.js
- web_modules/import-map.json
Adds search term to query parameters
Lets us:
* Track usage in google analytics
* Enables users to save searches via bookmarks
* Enables users to share searches as links
This completes part of https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/158 I didn't quite have enough time to add filters but I hope to work on that tomorrow. At least this way we can start tracking search
> add search term to query parameters

- src/index.js
This PR converts URLs in the content of the popup to clickable links. This PR does this for the "Seeking Volunteers" and "Notes" section.
This PR resolves #134
> convert URLs in popup content to links

- src/styles/styles.css
This changes the cursor to a pointer on map marker hover, to make it more clear that they are clickable.
I have no idea if this is the _right_ way to add styles to the mapbox marker, so I'd love @samanpwbb's perspective if there's a more appropriate way to do this.
(I couldn't take a screenshot because the cursor disappears from view whenever I tried)
> Change cursor to pointer on map marker hover

- src/index.js
This PR converts URLs in the content of the popup to clickable links. This PR does this for the "Accepting", "Not Accepting", and "Urgent Needs" section.
Originally, [PR 168](https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/168) only applied this change to the "Seeking Volunteers" and "Notes" section. However, a need for other columns was flagged by @comeoneileen in [Slack](https://opentwincities.slack.com/archives/C01525CPU5A/p1592021846431800?thread_ts=1592008433.420200&cid=C01525CPU5A).
> convert URLs in popup content to links part 2

- public/index.html
Works to accomplish the same thing as #180 , but with current/accurate use of gtag. 
The other cross-domain linking wasn't working, probably because it was an outdated method.
> Use gtag config for bi-directional cross-domain measurement

- docs/LANGUAGE_TRANSLATION.md
- specs/functional/language_button_spec.js
- src/index.js
LANGUAGE_TRANSLATIONS.md update + minor fix on first load with corresponding test
There's an issue where if you have a saved language, reload the screen and open the language selector, it will not have been translated. Changing the language after that does update the  welcome modal so this problem is on first load specifically.
> Translations doc update + minor fix

- README.md
Updates README to include info on TCMAP and volunteering. 
Better document the bridge between the OTC and TCMAP sides, and allow people a path there that isn't word of mouth.
No code changes :)
> Update README to include updated TCMAP & volunteer info

- public/index.html
- src/index.js
Fixed a bug in the volunteer sort so that it now sorts based on whether the "volunteers needed" badge is applied 
Sort by volunteers needed was not working properly
> made volunteers needed sort by volunteers badge

- public/index.html
- src/js/filter.js
- src/styles/search.css
- src/styles/styles.css
Moved the search bar to a fixed location beneath the site legend. Moved the "clear search" button to the left to make it more intuitive. Updated the styling of the search bar and "clear search" button to be more consistent with the style of the surrounding elements. 
The search bar used to be hidden by default on mobile devices with no clear indication of how to access it, and on all devices, the search bar would scroll out of view if navigating through the side-pane.
> Create fixed search bar

- public/index.html
- src/styles/styles.css
_A second attempt at a PR for adding the "we do our best but we might make a mistake, use tool at your own risk" disclaimer from the TCMAP.org FAQ to the help/info section of the website (second attempt because I didn't have the right permissions the first time, so the Travis build failed)._
_The lawyer suggested we do this._
> Adding the disclaimer to the help/info section (attempt #2)

- src/i18n/vie.json
Accent marks for the Vietnamese language selection were incorrect, updated them per recommendation of Simi in TCMAP
Resolve inaccurate accent marks in Vietnamese language selection
> fix the accents for Vietnamese language

- public/index.html
- src/index.js
Add gtag analytics to capture outbound link clicks
To improve analytics as per https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/184
> Add gtag analytics for outbound link clicks

- src/index.js
Fix the regex for extractUrl so that it doesn't capture punctuation at the end of urls, and inject http:// into the url string when it is missing so that the <a href...> tag works. 
Prior to this change, something like 'www.google.com,' wouldn't work for two reasons; the trailing comma would have been included in the url, and the lack of an explicit protocol at the beginning rendered the link unusable.
> fix link behavior to allow lack of web protocol and ignore end punctuation

- src/index.js
Fixing display of pop-up for the volunteers section
Because it was displaying incorrectly
> fix volunteer display in popup

- src/index.js
Add geolocate button to map that user can press to zoom in on their location.
Addresses this issue: https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/220
> Add user location to map

- src/index.js
Add line break in map popup text to match line breaks from google sheets. Currently, adds a full blank space between paragraphs. I can change to just add a newline if that would be preferred.
https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/231
> Add line breaks in map popups from line breaks in google sheets

- package-lock.json
- package.json
- public/index.html
- src/index.js
- src/styles/styles.css
Add pull to refresh functionality for mobile and remove the refresh button. Since all web browsers have a visible refresh button built in, it's not required to include is as an explicit button on the page. Also, pull-to-refresh is a fairly intuitive action on mobile devices so should be pretty natural fo most users.
Opens up screen real estate
> Pull to refresh

- public/index.html
- src/i18n/eng.json
- src/index.js
- src/styles/components/vote-banner.css
Convert covid banner to include voting information. Include countdown timer to Nov 3rd 8pm. When time expires, banner will change back to regular covid banner.
Help encourage people to vote.
> Add vote banner

- src/index.js
- src/styles/styles.css
Remove `Some Info Required` sections from popups. Move popup id badge next to money badge so all badges are in same location. 
`Some Info Required` was showing up as separate section on popups with TRUE or FALSE - not needed as the value is represented by the presence of the tag or not. Adjusted spacing of the popup a tiny bit so the tags were not smushed up against the next section on the popup.
> remove some info required separate section from popup

- public/index.html
- src/index.js
- src/styles/components/hours-banner.css
Adding hours may vary banner across top of site
Many sites  have unusual hours this week and we may not be able to keep up with all of them
> Add hours warning message

- src/index.js
- src/js/translator.js
Update the Google Analytics language_change event so it only triggers when the user first comes to the website, and every time they open the welcome popup and select a language. It used to be triggering every time someone would reload the page as well
To fix issue #178, also related to #154
> Analytics: update "language_change" Event to better represent users actions

- public/index.html
Set hours banner to not display.
Not relevant anymore (but will be relevant in a few weeks again so leaving code in place)
> Stop displaying hours banner"

- specs/helpers.js
- src/index.js
- src/js/hiatus-modal.js
- src/js/welcome.js
- src/styles/components/hiatus-modal.css
This branch introduces a modal window that opens once per session after language has been set. It alerts users
that site hours and info will not be up to date during TCMAP's 3/1 - 3/7 hiatus.  
Alerts users to critical information that affects how they are able to use the site.
> Issue na/teroknora/hiatus alertdialog modal

- src/js/hiatus-modal.js
Bugfix - remove animate from modal close
> Try removing animate from hiatus close

- public/index.html
- specs/helpers.js
- src/index.js
- src/js/hiatus-modal.js
Remove hiatus banner and modal (will not be merging until later tonight)
Hiatus will be over tonight
> remove hiatus banner and hiatus modal

- src/index.js
Removed "Not Accepting" from list of searchable fields.
Currently, search results include sites where a search query is listed in the "Not Accepting" category. This leads to false positives in the context of what is reasonable to consider the most common user intent (to locate sites where an item can be donated or received). E.g., a search for "clothing" returns both sites that _are accepting_ clothing and sites that _are not accepting_ clothing which is confusing and unhelpful for the user.
> removed 'not accepting' from search fields

- public/index.html
- src/index.js
Set display of memorial day hours banner to none.
Not currently applicable. Setting to none rather than deleting in case we want to repurpose for the recently proposed "[take the survey banner".](https://tcmap.slack.com/archives/C017F4NDQAH/p1622515771041800?thread_ts=1622227336.032100&cid=C017F4NDQAH)
> Hide memorial day banner
